### ISSUE TITLE
Help reproducing benchmarks

### ISSUE THREAD

**Issue by bb7332193** [andylolu2/cuda-nn#2]
Hello, thanks for making such a useful educational resource. I am trying to replicate the reported ~2s benchmark However, when I run `train_mnist.cpp` and `train_mnist.py` I obtain the following timings:

**train_mnist.cpp /tmp/cuda/data 10000 128 0**
```
Step: 9500, loss: 0.430664
Step: 9600, loss: 0.437988
Step: 9700, loss: 0.3125
Step: 9800, loss: 0.356201
Step: 9900, loss: 0.452148
Step: 10000, loss: 0.320557
Duration: 16.357s
```

**train_mnist.py 10000 128 0**
```
Step: 9600, loss: 0.3048
Step: 9700, loss: 0.3932
Step: 9800, loss: 0.2125
Step: 9900, loss: 0.3596
Step: 10000, loss: 0.6062
Duration: 16.7701s
```

Evidently, these are quite far off the mark. I believe this is likely due to hardware differences on my machine:
```
	 * Name: NVIDIA GeForce GTX 1650 Ti with Max-Q Design
	 * Compute capability: 7.5
	 * Number of SMs: 16
	 * Registers per Multiprocessor: 65536
	 * Max threads per SM: 1024
```

Is it possible to obtain similar performance on my hardware? Could you point me in the right direction to understand the required changes to the code, if any?

**Comment by andylolu2** [comment]
The code is optimised for Turing architecture (e.g. RTX 2000 series, T4 etc.) and it makes use of tensor cores for faster matmul — I don't think your GPU has those so it makes sense that it's much slower.
(I'm surprised it even compiled)

The specs say that your 1650Ti Max-Q is capable of ~3TFLOPs, while the GPU I I tested on (2060 Max-Q) is capable of ~26TFLOPs (with tensor core). So I think it's expected that your benchmark runs 8-9 times slower. In other words, your numbers are pretty close to optimal for your hardware.

**Comment by andylolu2** [comment]
The code makes use of tensor cores for faster matmul — I don't think your GPU has those so it makes sense that it's much slower.
(I'm surprised it even compiled)

The specs say that your 1650Ti Max-Q is capable of ~3TFLOPs, while the GPU I tested on (2060 Max-Q) is capable of ~26TFLOPs (with tensor core). So I think it's expected that your benchmark runs 8-9 times slower. In other words, your numbers are pretty close to optimal for your hardware.

**Comment by bb7332193** [comment]
Thanks for the pointers, indeed that makes sense. 

I believe it compiled as my 1650 utilizes the same Turing architecture and compute capability as your 2060.
